# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03418755a0cdba93c3ec6923b0e6becdb7645e31a487913aed5a8680ac3d7fdea74a0da5554bf7d30c7a1bbb17c5c619ac9202a2e658650599c9b6ad8ae501b4

test:
  secret_key_base: 93d1c8f2bf64b1cfc9458eb14c16d7c6e4c6c3336c3ff65a1188d10e46d515e2e1829fd202f67845505da78c73760d3a0a83f73db2dbeec9d95cc76bdfaa92ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
